exporter.fhir.export = true
exporter.fhir.version = R4
exporter.csv.export = false
exporter.ccda.export = false
exporter.hospital.fhir.export = false
exporter.practitioner.fhir.export = false
generate.reference_date = 20221231
generate.years_of_history = 10
exporter.baseDirectory = data/raw/synthea_generated/
